### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pyh007** [Yueming6568/DeltaEdit#13]
Loading stylegan weights from pretrained!
Traceback (most recent call last):
  File "/home/akira/DeltaEdit/scripts/inference_real.py", line 206, in <module>
    main(opts)
  File "/home/akira/DeltaEdit/scripts/inference_real.py", line 189, in main
    fake_delta_s = net(latent_s, delta_c)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/akira/DeltaEdit/./delta_mapper.py", line 60, in forward
    x_coarse = torch.cat([s_coarse, torch.stack([c_coarse]*3, dim=1)], dim=2) #[b,3,1024]
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 2 but got size 1 for tensor number 1 in the list.
我自己上传了一张图片，为什么报这个错误了

**Comment by Yueming6568** [comment]
You may debug the shapes of your uploaded images. Thank you!
