### ISSUE TITLE
RuntimeError: Function FusedLeakyReLUFunctionBackward 

### ISSUE THREAD

**Issue by Ashly555** [Yueming6568/DeltaEdit#18]
I really like your work. I've encountered a problem using DeltaEdit for a different field, but during the training process, I encountered the following error:

Traceback (most recent call last): File "scripts/train.py", line 63, in <module> main(opts) File "scripts/train.py", line 52, in main loss.backward() File "/root/autodl-tmp/conda/envs/Del/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph) File "/root/autodl-tmp/conda/envs/Del/lib/python3.8/site-packages/torch/autograd/init.py", line 130, in backward Variable._execution_engine.run_backward( RuntimeError: Function FusedLeakyReLUFunctionBackward returned an invalid gradient at index 1 - got [4] but expected shape compatible with [512]

Is there any solution to this problem?

**Comment by br0kyy** [comment]
HI,have u solve the problem?Cause i have encountered  the same problem.

**Comment by visa980911** [comment]
HI,have u solve the problem?Cause i have encountered the same problem.

**Comment by visa980911** [comment]
> HI,have u solve the problem?Cause i have encountered the same problem.

HI,have u solve the problem?Cause i have encountered the same problem.

**Comment by Yueming6568** [comment]
Thank you for your interest! We haven’t encountered this issue in our experiments. Please try switching your environment—our method has been verified to work with ​Python 3.8 + PyTorch 1.7 or 1.12.
